server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:order
    username: root
    password: Gaffoor2424
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE
  config:
    import: optional:configserver:http://localhost:9296



eureka:
  client:
    enabled: false