server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:order
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL:localhost}:9296



eureka:
  client:
    enabled: false